// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email, role, password
) VALUES (
  $1, $2, $3, $4
)RETURNING id, created_at, id, name, email, role, password, reset_password_token, reset_password_expire, confirm_email_token, is_email_confirmed, two_factor_code, two_factor_code_expire, two_factor_enable, created_at
`

type CreateUserParams struct {
	Name     string   `json:"name"`
	Email    string   `json:"email"`
	Role     UserRole `json:"role"`
	Password string   `json:"password"`
}

type CreateUserRow struct {
	ID                  int64        `json:"id"`
	CreatedAt           sql.NullTime `json:"created_at"`
	ID_2                int64        `json:"id_2"`
	Name                string       `json:"name"`
	Email               string       `json:"email"`
	Role                UserRole     `json:"role"`
	Password            string       `json:"password"`
	ResetPasswordToken  string       `json:"reset_password_token"`
	ResetPasswordExpire time.Time    `json:"reset_password_expire"`
	ConfirmEmailToken   string       `json:"confirm_email_token"`
	IsEmailConfirmed    bool         `json:"is_email_confirmed"`
	TwoFactorCode       string       `json:"two_factor_code"`
	TwoFactorCodeExpire time.Time    `json:"two_factor_code_expire"`
	TwoFactorEnable     bool         `json:"two_factor_enable"`
	CreatedAt_2         sql.NullTime `json:"created_at_2"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Password,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ID_2,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpire,
		&i.ConfirmEmailToken,
		&i.IsEmailConfirmed,
		&i.TwoFactorCode,
		&i.TwoFactorCodeExpire,
		&i.TwoFactorEnable,
		&i.CreatedAt_2,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, role, password, reset_password_token, reset_password_expire, confirm_email_token, is_email_confirmed, two_factor_code, two_factor_code_expire, two_factor_enable, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (Users, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpire,
		&i.ConfirmEmailToken,
		&i.IsEmailConfirmed,
		&i.TwoFactorCode,
		&i.TwoFactorCodeExpire,
		&i.TwoFactorEnable,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, password, reset_password_token, reset_password_expire, confirm_email_token, is_email_confirmed, two_factor_code, two_factor_code_expire, two_factor_enable, created_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Users
	for rows.Next() {
		var i Users
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Password,
			&i.ResetPasswordToken,
			&i.ResetPasswordExpire,
			&i.ConfirmEmailToken,
			&i.IsEmailConfirmed,
			&i.TwoFactorCode,
			&i.TwoFactorCodeExpire,
			&i.TwoFactorEnable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  SET name = $2,
      email = $3,
      role = $4,
      password = $5
WHERE id = $1
RETURNING id, name, email, role, password, reset_password_token, reset_password_expire, confirm_email_token, is_email_confirmed, two_factor_code, two_factor_code_expire, two_factor_enable, created_at
`

type UpdateUserParams struct {
	ID       int64    `json:"id"`
	Name     string   `json:"name"`
	Email    string   `json:"email"`
	Role     UserRole `json:"role"`
	Password string   `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Password,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Password,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpire,
		&i.ConfirmEmailToken,
		&i.IsEmailConfirmed,
		&i.TwoFactorCode,
		&i.TwoFactorCodeExpire,
		&i.TwoFactorEnable,
		&i.CreatedAt,
	)
	return i, err
}
